sudo: false
language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - pip install coveralls tox-travis

script:
  - tox

matrix:
  fast_finish: true

after_success:
  - coveralls
